config/routes.rb
VentOut::Application.routes.draw do
  resources :backgrounds

  resources :posts

end

app/models/background.rb
class Background < ActiveRecord::Base
  attr_accessible :filename, :title
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :bg
  attr_accessible :color, :size, :text
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/backgrounds_controller.rb
class BackgroundsController < ApplicationController
  # GET /backgrounds
  # GET /backgrounds.json
  def index
    @backgrounds = Background.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @backgrounds }
    end
  end

  # GET /backgrounds/1
  # GET /backgrounds/1.json
  def show
    @background = Background.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @background }
    end
  end

  # GET /backgrounds/new
  # GET /backgrounds/new.json
  def new
    @background = Background.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @background }
    end
  end

  # GET /backgrounds/1/edit
  def edit
    @background = Background.find(params[:id])
  end

  # POST /backgrounds
  # POST /backgrounds.json
  def create
    @background = Background.new(params[:background])
		file_to_upload = params[:background][:filename]
		@background.filename = file_to_upload.original_filename

		File.open(Rails.root.join('public', file_to_upload.original_filename), 'wb') do |file|
    	file.write(file_to_upload.read)
  	end

    respond_to do |format|
      if @background.save
        format.html { redirect_to @background, notice: 'Background was successfully created.' }
        format.json { render json: @background, status: :created, location: @background }
      else
        format.html { render action: "new" }
        format.json { render json: @background.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /backgrounds/1
  # PUT /backgrounds/1.json
  def update
    @background = Background.find(params[:id])

    respond_to do |format|
      if @background.update_attributes(params[:background])
        format.html { redirect_to @background, notice: 'Background was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @background.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /backgrounds/1
  # DELETE /backgrounds/1.json
  def destroy
    @background = Background.find(params[:id])
    @background.destroy

    respond_to do |format|
      format.html { redirect_to backgrounds_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/backgrounds_helper.rb
module BackgroundsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/backgrounds/_form.html.erb
<%= form_for(@background) do |f| %>
  <% if @background.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@background.errors.count, "error") %> prohibited this background from being saved:</h2>

      <ul>
      <% @background.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :filename %><br />
    <%= f.file_field :filename, :accept => 'image/png,image/gif,image/jpeg' %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/backgrounds/edit.html.erb
<h1>Editing background</h1>

<%= render 'form' %>

<%= link_to 'Show', @background %> |
<%= link_to 'Back', backgrounds_path %>

app/views/backgrounds/index.html.erb
<h1>Listing backgrounds</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Filename</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @backgrounds.each do |background| %>
  <tr>
    <td><%= background.title %></td>
    <td><%= background.filename %></td>
    <td><%= link_to 'Show', background %></td>
    <td><%= link_to 'Edit', edit_background_path(background) %></td>
    <td><%= link_to 'Destroy', background, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Background', new_background_path %>

app/views/backgrounds/new.html.erb
<h1>New background</h1>

<%= render 'form' %>

<%= link_to 'Back', backgrounds_path %>

app/views/backgrounds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @background.title %>
</p>

<p>
  <b>Filename:</b>
  <%= @background.filename %>
</p>


<%= link_to 'Edit', edit_background_path(@background) %> |
<%= link_to 'Back', backgrounds_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>VentOut</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :size %><br />
    <%= f.text_field :size %>
  </div>
  <div class="field">
    <%= f.label :color %><br />
    <%= f.text_field :color %>
  </div>
  <div class="field">
    <%= f.label :bg %><br />
    <%= f.text_field :bg %>
  </div>
  <div class="field">
    <%= f.label :text %><br />
    <%= f.text_field :text %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Listing posts</h1>

<table>
  <tr>
    <th>Size</th>
    <th>Color</th>
    <th>Bg</th>
    <th>Text</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @posts.each do |post| %>
  <tr>
    <td><%= post.size %></td>
    <td><%= post.color %></td>
    <td><%= post.bg %></td>
    <td><%= post.text %></td>
    <td><%= link_to 'Show', post %></td>
    <td><%= link_to 'Edit', edit_post_path(post) %></td>
    <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Size:</b>
  <%= @post.size %>
</p>

<p>
  <b>Color:</b>
  <%= @post.color %>
</p>

<p>
  <b>Bg:</b>
  <%= @post.bg %>
</p>

<p>
  <b>Text:</b>
  <%= @post.text %>
</p>


<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>